### ISSUE TITLE
发生异常: AttributeError

### ISSUE THREAD

**Issue by y1511** [our0boros/SFacgDownloader#1]
发生异常: AttributeError
'NoneType' object has no attribute 'span'
  File "E:\SFacgDownloader-main\SFacgDownloader.py", line 279, in <module>
    idx_loc = re.search('class="item bold">', html, flags=0).span()

大佬这咋回事呀

**Comment by our0boros** [comment]
你再确认一下提供的cURL信息的网址是不是对应某本书的某一章节，上面报错是因为读取不到对应的网页元素造成的。
对应的网址应该是 https://book.sfacg.com/Novel/<书籍id>/<分段id>/<章节id>/

**Comment by y1511** [comment]
好的，我知道我哪里有问题了。我打开控制端的时候选择的是手机模式。问题已经解决了，感谢大佬
